### ISSUE TITLE
pause with datetime object fails with Python 2.7.8.

### ISSUE THREAD

**Issue by t-w3nz** [jgillick/python-pause#1]
I get following error. I mean to know, that it work for me with Python 2.7.5.

```
Python 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pause, datetime
>>> dt = datetime.datetime(2013, 6, 2, 14, 36, 34, 383752)
>>> pause.until(dt)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\pause\__init__.py", line 46, in until
    end = float(time.strftime('%s.%f'))
ValueError: Invalid format string
```

**Comment by David-OConnor** [comment]
Same, on 3.4.

**Comment by zed** [comment]
It works on Ubuntu because [`strftime(3)`](http://man7.org/linux/man-pages/man3/strftime.3.html) on that platform accepts `"%s"` format directive. Python does not support `strftime("%s")`. It should not be used in portable scripts

**Comment by hockeymikey** [comment]
Someone should fix this.

**Comment by jgillick** [comment]
I'm not actively maintaining this right now, but would happily take a pull request, if someone wanted to try fixing it.

**Comment by ferret-guy** [comment]
Just checked in windows with python 2.7.9 and it seems to work great! @jgillick can you close this issue?

**Comment by jgillick** [comment]
Excellent. Thank you!

**Comment by dreadsoul** [comment]
Hey guys, I have got python 2.9.13 and Win10 but still got the same problem. How to solve it? Could you give some advices,pls

**Comment by robkau** [comment]
Hey Dreadsoul can you post the full error message that shows up?

**Comment by jon-is-me** [comment]
I'm having the same issue

```
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> import pause, datetime

>>> dt = datetime.datetime(2013, 6, 2, 14, 36, 34, 383752)

>>> pause.until(dt)


Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    pause.until(dt)
  File "C:\Python27\lib\site-packages\pause\__init__.py", line 46, in until
    end = float(time.strftime('%s.%f'))
ValueError: Invalid format string
>>> 
```

**Comment by t-w3nz** [comment]
`pip install --upgrade git+https://github.com/jgillick/python-pause` will solve it, because it's not included in the latest release.
