### ISSUE TITLE
supporting pause.until(dt) with offset aware datetime

### ISSUE THREAD

**Issue by kaiott** [jgillick/python-pause#10]
I've found that when I try to execute `pause.until(dt)` I get an exception: `can't subtract offset-naive and offset-aware datetimes`. Presumably in your code (didn't check it) you subtract dt - datetime.now(). Could be fixed easily, I think, by using datetime.now().astimezone() if the input is offset-aware.

**Comment by jgillick** [comment]
If you give it a try and make it work, feel free to submit a pull request for the fix.

**Comment by kaiott** [comment]
Ehm, I just checked and there exists an open pull request from August 1, 2019 that should solve this issues. I suggest you look at that and accept it
